services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend_project.backend_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: 23483m4i+o88yz&_qozr=ks353rzfa^e&4&ym(o!oi##vs@b4k
      - key: TELEGRAM_TOKEN
        value: 866305374:AAHojs8wxQZyUY4Syb0gvbUIwPvHMbmys9U
      - key: TELEGRAM_CHAT_ID
        value: 1101300918
    autoDeploy: true

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend_project.backend_project worker --loglevel=info --pool=solo
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: 23483m4i+o88yz&_qozr=ks353rzfa^e&4&ym(o!oi##vs@b4k
      - key: TELEGRAM_TOKEN
        value: 866305374:AAHojs8wxQZyUY4Syb0gvbUIwPvHMbmys9U
      - key: TELEGRAM_CHAT_ID
        value: 1101300918
      - key: REDIS_URL
        value: redis://default:tgQAIqUwV5KXODLFCwQkPa4FZepdShPL@redis-12326.c62.us-east-1-4.ec2.redns.redis-cloud.com:12326


  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 866305374:AAHojs8wxQZyUY4Syb0gvbUIwPvHMbmys9U
