services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend_project.backend_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: TELEGRAM_TOKEN
        value: your-telegram-bot-token
      - key: TELEGRAM_CHAT_ID
        value: your-chat-id
    autoDeploy: true

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend_project.backend_project worker --loglevel=info --pool=solo
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: TELEGRAM_TOKEN
        value: your-telegram-bot-token
      - key: TELEGRAM_CHAT_ID
        value: your-chat-id
      - key: REDIS_URL
        value: redis://default:<password>@<host>:<port>
