services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend_project.backend_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-actual-secret-key
      - key: TELEGRAM_TOKEN
        value: 123456789:ABC...yourToken
      - key: TELEGRAM_CHAT_ID
        value: 123456789
    autoDeploy: true

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend_project.backend_project worker --loglevel=info --pool=solo
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-actual-secret-key
      - key: TELEGRAM_TOKEN
        value: 123456789:ABC...yourToken
      - key: TELEGRAM_CHAT_ID
        value: 123456789
      - key: REDIS_URL
        value: redis://default:yourPass@redis-xxxx.cxx.us-east-1-4.ec2.redns.redis-cloud.com:xxxxx

  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 123456789:ABC...yourToken
